//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupo()
        {
            this.SubGrupos = new HashSet<SubGrupo>();
            this.Detalle_Grupo_Patros = new HashSet<Detalle_Grupo_Patro>();
        }
    
        public int Id { get; set; }
        public string Cod_Grupo { get; set; }
        public string Nombre_Grupo { get; set; }
        public int Num_Solicitud { get; set; }
        public byte Pañoleta { get; set; }
        public byte Insignia { get; set; }
        public byte Sello_Grupo { get; set; }
        public int ResponsableId { get; set; }
        public int DistritoId { get; set; }
        public byte Carta_Solicitud { get; set; }
    
        public virtual Responsable Responsable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubGrupo> SubGrupos { get; set; }
        public virtual Distrito Distrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Grupo_Patro> Detalle_Grupo_Patros { get; set; }
    }
}
