//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membresia_Juvenil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membresia_Juvenil()
        {
            this.Progresion_Juveniles = new HashSet<Progresion_Juvenil>();
        }
    
        public int Id { get; set; }
        public int SubGrupoId { get; set; }
        public int JuvenilId { get; set; }
        public int TutorId { get; set; }
    
        public virtual SubGrupo SubGrupo { get; set; }
        public virtual Juvenil Juvenil { get; set; }
        public virtual Tutor Tutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Progresion_Juvenil> Progresion_Juveniles { get; set; }
    }
}
