//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membresia_Adulto
    {
        public int Id { get; set; }
        public byte Carta_Compromiso { get; set; }
        public byte Carta_Intencion { get; set; }
        public byte Record_Policia { get; set; }
        public byte Carta_Ref_Personal { get; set; }
        public byte Certifi_Salvo_Peligro { get; set; }
        public string Annio { get; set; }
        public int Etapa_AprobacionId { get; set; }
        public int AdultoId { get; set; }
    
        public virtual Etapa_Aprobacion Etapa_Aprobacion { get; set; }
        public virtual Adulto Adulto { get; set; }
    }
}
