//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeloNiscoutFBLContainer : DbContext
    {
        public ModeloNiscoutFBLContainer()
            : base("name=ModeloNiscoutFBLContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<Periodo> Periodos { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Municipio> Municipios { get; set; }
        public virtual DbSet<Sector> Sectores { get; set; }
        public virtual DbSet<Distrito> Distritos { get; set; }
        public virtual DbSet<Evento> Eventos { get; set; }
        public virtual DbSet<Membresia_Adulto> Membresia_Adultos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Membresia_Juvenil> Membresia_Juveniles { get; set; }
        public virtual DbSet<SubGrupo> SubGrupos { get; set; }
        public virtual DbSet<Grupo> Grupos { get; set; }
        public virtual DbSet<Etapa_Aprobacion> Etapa_Aprobaciones { get; set; }
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Juvenil> Juveniles { get; set; }
        public virtual DbSet<Centro_Estudio> Centro_Estudios { get; set; }
        public virtual DbSet<Tipo_Grupo> Tipo_Grupos { get; set; }
        public virtual DbSet<Progresion_Juvenil> Progresion_Juveniles { get; set; }
        public virtual DbSet<Detalle_Evento_Patro> Detalle_Evento_Patros { get; set; }
        public virtual DbSet<Detalle_Grupo_Patro> Detalle_Grupo_Patros { get; set; }
        public virtual DbSet<Local_Evento> Local_Eventos { get; set; }
        public virtual DbSet<Asistente_Evento> Asistente_Eventos { get; set; }
        public virtual DbSet<Adulto> Adultos { get; set; }
        public virtual DbSet<Asistente> Asistentes { get; set; }
        public virtual DbSet<Responsable> Responsables { get; set; }
        public virtual DbSet<Patrocinador> Patrocinadores { get; set; }
        public virtual DbSet<Personal_Admon> Personal_Admon { get; set; }
        public virtual DbSet<Tutoria> Tutorias { get; set; }
        
    }
}
