//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progresion_Juvenil
    {
        public int Id { get; set; }
        public string Cod_Etapa_Prog { get; set; }
        public string Descripcion_Etapa { get; set; }
        public int Membresia_JuvenilId { get; set; }
    
        public virtual Membresia_Juvenil Membresia_Juvenil { get; set; }
    }
}
