//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NiscoutFBL2019.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public int Id { get; set; }
        public string Cod_Sector { get; set; }
        public string Nombre_Sector { get; set; }
        public int MunicipioId { get; set; }
        public int DistritoId { get; set; }
    
        public virtual Municipio Municipio { get; set; }
        public virtual Distrito Distrito { get; set; }
    }
}
